/**
 * Render TypeScript modules from parsed KERIpy CESR table data.
 *
 * The parser in `generate-tables.ts` owns reading Python source. This module
 * owns only deterministic TypeScript rendering so generated-code templates do
 * not live as multiline strings inside the parser.
 */

/** Parsed KERIpy `Sizage` values for Matter code tables. */
export interface MatterSize {
  /** Hard-code size. */
  hs: number;
  /** Soft-code size. */
  ss: number;
  /** Extra payload size. */
  xs: number;
  /** Full size, or null when KERIpy declares `None`. */
  fs: number | null;
  /** Lead size. */
  ls: number;
}

/** Parsed KERIpy `Xizage` values for Indexer code tables. */
export interface IndexerSize {
  /** Hard-code size. */
  hs: number;
  /** Soft-code size. */
  ss: number;
  /** Other-index size. */
  os: number;
  /** Full size, or null when KERIpy declares `None`. */
  fs: number | null;
  /** Lead size. */
  ls: number;
}

/** Parsed KERIpy `Cizage` values for Counter code tables. */
export interface CounterSize {
  /** Hard-code size. */
  hs: number;
  /** Soft-code size. */
  ss: number;
  /** Full size. */
  fs: number;
}

function generatedHeader(): string[] {
  return ["// Generated by packages/cesr/scripts/generate-tables.ts"];
}

function q(value: string): string {
  return JSON.stringify(value);
}

function sortedEntries<T>(record: Record<string, T>): Array<[string, T]> {
  return Object.entries(record).sort(([a], [b]) => a.localeCompare(b));
}

function renderMatterSize(size: MatterSize): string {
  const fs = size.fs === null ? "null" : String(size.fs);
  return `{ hs: ${size.hs}, ss: ${size.ss}, xs: ${size.xs}, fs: ${fs}, ls: ${size.ls} }`;
}

function renderIndexerSize(size: IndexerSize): string {
  const fs = size.fs === null ? "null" : String(size.fs);
  return `{ hs: ${size.hs}, ss: ${size.ss}, os: ${size.os}, fs: ${fs}, ls: ${size.ls} }`;
}

function renderCounterSize(size: CounterSize): string {
  return `{ hs: ${size.hs}, ss: ${size.ss}, fs: ${size.fs} }`;
}

function renderMapEntries<T>(
  record: Record<string, T>,
  renderValue: (value: T) => string,
): string[] {
  return sortedEntries(record).map(([code, value]) => `  [${q(code)}, ${renderValue(value)}],`);
}

function renderNameObject(name: string, entries: Array<[string, string]>): string[] {
  return [
    `export const ${name} = {`,
    ...entries.map(([code, value]) => `  ${q(code)}: ${q(value)},`),
    "} as const;",
  ];
}

/** Render Matter size/name tables plus re-exported static hard-code tables. */
export function renderMatterTables(
  sizes: Record<string, MatterSize>,
  names: Record<string, string>,
): string {
  const inverseEntries = sortedEntries(names).sort(([, a], [, b]) => a.localeCompare(b)).map(
    ([code, name]) => [name, code] as [string, string],
  );
  return [
    ...generatedHeader(),
    "import type { Sizage } from \"./table-types.ts\";",
    "export { MATTER_HARDS } from \"./hard-code-tables.ts\";",
    "",
    "export const MATTER_SIZES = new Map<string, Sizage>([",
    ...renderMapEntries(sizes, renderMatterSize),
    "]);",
    "",
    ...renderNameObject("MATTER_CODE_NAMES", sortedEntries(names)),
    "",
    ...renderNameObject("MATTER_CODES_BY_NAME", inverseEntries),
    "",
  ].join("\n");
}

/** Render Indexer size/name tables plus re-exported static hard-code tables. */
export function renderIndexerTables(
  sizes: Record<string, IndexerSize>,
  names: Record<string, string>,
): string {
  const inverseEntries = sortedEntries(names).sort(([, a], [, b]) => a.localeCompare(b)).map(
    ([code, name]) => [name, code] as [string, string],
  );
  return [
    ...generatedHeader(),
    "import type { Xizage } from \"./table-types.ts\";",
    "export { INDEXER_HARDS } from \"./hard-code-tables.ts\";",
    "",
    "export const INDEXER_SIZES = new Map<string, Xizage>([",
    ...renderMapEntries(sizes, renderIndexerSize),
    "]);",
    "",
    ...renderNameObject("INDEXER_CODE_NAMES", sortedEntries(names)),
    "",
    ...renderNameObject("INDEXER_CODES_BY_NAME", inverseEntries),
    "",
  ].join("\n");
}

/** Render simple string-set codex modules such as cold/ilk/trait codexes. */
export function renderStringCodexes(
  codexes: Array<{ constName: string; entries: Record<string, string> }>,
): string {
  const lines = generatedHeader();
  for (const [index, { constName, entries }] of codexes.entries()) {
    if (index > 0) {
      lines.push("");
    }
    lines.push(`export const ${constName} = new Set<string>([`);
    lines.push(...Object.keys(entries).sort((a, b) => a.localeCompare(b)).map((code) => `  ${q(code)},`));
    lines.push("]);");
  }
  lines.push("");
  return lines.join("\n");
}

/** Render canonical codex object modules with instance and type aliases. */
export function renderCanonicalCodexModule(
  codexes: Array<{
    className: string;
    instanceName: string;
    entries: Record<string, string>;
  }>,
): string {
  const lines = generatedHeader();
  for (const [index, { className, instanceName, entries }] of codexes.entries()) {
    if (index > 0) {
      lines.push("");
    }
    lines.push(`export const ${className} = Object.freeze(`);
    lines.push("  {");
    lines.push(...sortedEntries(entries).map(([name, code]) => `    ${name}: ${q(code)},`));
    lines.push("  } as const,");
    lines.push(");");
    lines.push("");
    lines.push(`export const ${instanceName} = ${className};`);
    lines.push("");
    lines.push(`export type ${className}Name = keyof typeof ${className};`);
    lines.push(`export type ${className}Code = (typeof ${className})[${className}Name];`);
  }
  lines.push("");
  return lines.join("\n");
}

/** Render Counter v1/v2 size and name tables plus static hard-code tables. */
export function renderCounterTables(
  v1: Record<string, CounterSize>,
  v2: Record<string, CounterSize>,
  namesV1: Record<string, string>,
  namesV2: Record<string, string>,
): string {
  return [
    ...generatedHeader(),
    "import type { Cizage } from \"./table-types.ts\";",
    "export { COUNTER_HARDS } from \"./hard-code-tables.ts\";",
    "",
    "export const COUNTER_SIZES_V1 = new Map<string, Cizage>([",
    ...renderMapEntries(v1, renderCounterSize),
    "]);",
    "",
    "export const COUNTER_SIZES_V2 = new Map<string, Cizage>([",
    ...renderMapEntries(v2, renderCounterSize),
    "]);",
    "",
    ...renderNameObject("COUNTER_CODE_NAMES_V1", sortedEntries(namesV1)),
    "",
    ...renderNameObject("COUNTER_CODE_NAMES_V2", sortedEntries(namesV2)),
    "",
  ].join("\n");
}
