// Generated by scripts/generate-tables.ts
import type { Cizage } from "./table-types.ts";

export const COUNTER_SIZES_V1 = new Map<string, Cizage>([
  ["-A", { hs: 2, ss: 2, fs: 4 }],
  ["-B", { hs: 2, ss: 2, fs: 4 }],
  ["-C", { hs: 2, ss: 2, fs: 4 }],
  ["-D", { hs: 2, ss: 2, fs: 4 }],
  ["-E", { hs: 2, ss: 2, fs: 4 }],
  ["-F", { hs: 2, ss: 2, fs: 4 }],
  ["-G", { hs: 2, ss: 2, fs: 4 }],
  ["-H", { hs: 2, ss: 2, fs: 4 }],
  ["-I", { hs: 2, ss: 2, fs: 4 }],
  ["-J", { hs: 2, ss: 2, fs: 4 }],
  ["-K", { hs: 2, ss: 2, fs: 4 }],
  ["-L", { hs: 2, ss: 2, fs: 4 }],
  ["-V", { hs: 2, ss: 2, fs: 4 }],
  ["--AAA", { hs: 5, ss: 3, fs: 8 }],
  ["--A", { hs: 3, ss: 5, fs: 8 }],
]);

export const COUNTER_SIZES_V2 = new Map<string, Cizage>(COUNTER_SIZES_V1);

export const COUNTER_HARDS = new Map<string, number>([
  ..."ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split("").map((c) =>
    [`-${c}`, 2] as [string, number]
  ),
  ["--", 3],
  ["-_", 5],
]);

export const COUNTER_CODE_NAMES = {
  "-A": "ControllerIdxSigs",
  "-B": "WitnessIdxSigs",
  "-C": "NonTransReceiptCouples",
  "-D": "TransReceiptQuadruples",
  "-E": "FirstSeenReplayCouples",
  "-F": "TransIdxSigGroups",
  "-G": "SealSourceCouples",
  "-H": "TransLastIdxSigGroups",
  "-I": "SealSourceTriples",
  "-J": "SadPathSig",
  "-K": "SadPathSigGroup",
  "-L": "PathedMaterialQuadlets",
  "-V": "AttachedMaterialQuadlets",
  "--AAA": "KERIACDCGenusVersion",
} as const;
