// Generated by packages/cesr/scripts/generate-tables.ts
export const IndexerCodex = Object.freeze(
  {
    ECDSA_256k1_Big_Crt_Sig: "2D",
    ECDSA_256k1_Big_Sig: "2C",
    ECDSA_256k1_Crt_Sig: "D",
    ECDSA_256k1_Sig: "C",
    ECDSA_256r1_Big_Crt_Sig: "2F",
    ECDSA_256r1_Big_Sig: "2E",
    ECDSA_256r1_Crt_Sig: "F",
    ECDSA_256r1_Sig: "E",
    Ed25519_Big_Crt_Sig: "2B",
    Ed25519_Big_Sig: "2A",
    Ed25519_Crt_Sig: "B",
    Ed25519_Sig: "A",
    Ed448_Big_Crt_Sig: "3B",
    Ed448_Big_Sig: "3A",
    Ed448_Crt_Sig: "0B",
    Ed448_Sig: "0A",
    TBD0: "0z",
    TBD1: "1z",
    TBD4: "4z",
  } as const,
);

export const IdrDex = IndexerCodex;

export type IndexerCodexName = keyof typeof IndexerCodex;
export type IndexerCodexCode = (typeof IndexerCodex)[IndexerCodexName];

export const IndexedSigCodex = Object.freeze(
  {
    ECDSA_256k1_Big_Crt_Sig: "2D",
    ECDSA_256k1_Big_Sig: "2C",
    ECDSA_256k1_Crt_Sig: "D",
    ECDSA_256k1_Sig: "C",
    ECDSA_256r1_Big_Crt_Sig: "2F",
    ECDSA_256r1_Big_Sig: "2E",
    ECDSA_256r1_Crt_Sig: "F",
    ECDSA_256r1_Sig: "E",
    Ed25519_Big_Crt_Sig: "2B",
    Ed25519_Big_Sig: "2A",
    Ed25519_Crt_Sig: "B",
    Ed25519_Sig: "A",
    Ed448_Big_Crt_Sig: "3B",
    Ed448_Big_Sig: "3A",
    Ed448_Crt_Sig: "0B",
    Ed448_Sig: "0A",
  } as const,
);

export const IdxSigDex = IndexedSigCodex;

export type IndexedSigCodexName = keyof typeof IndexedSigCodex;
export type IndexedSigCodexCode = (typeof IndexedSigCodex)[IndexedSigCodexName];

export const IndexedCurrentSigCodex = Object.freeze(
  {
    ECDSA_256k1_Big_Crt_Sig: "2D",
    ECDSA_256k1_Crt_Sig: "D",
    ECDSA_256r1_Big_Crt_Sig: "2F",
    ECDSA_256r1_Crt_Sig: "F",
    Ed25519_Big_Crt_Sig: "2B",
    Ed25519_Crt_Sig: "B",
    Ed448_Big_Crt_Sig: "3B",
    Ed448_Crt_Sig: "0B",
  } as const,
);

export const IdxCrtSigDex = IndexedCurrentSigCodex;

export type IndexedCurrentSigCodexName = keyof typeof IndexedCurrentSigCodex;
export type IndexedCurrentSigCodexCode =
  (typeof IndexedCurrentSigCodex)[IndexedCurrentSigCodexName];

export const IndexedBothSigCodex = Object.freeze(
  {
    ECDSA_256k1_Big_Sig: "2C",
    ECDSA_256k1_Sig: "C",
    ECDSA_256r1_Big_Sig: "2E",
    ECDSA_256r1_Sig: "E",
    Ed25519_Big_Sig: "2A",
    Ed25519_Sig: "A",
    Ed448_Big_Sig: "3A",
    Ed448_Sig: "0A",
  } as const,
);

export const IdxBthSigDex = IndexedBothSigCodex;

export type IndexedBothSigCodexName = keyof typeof IndexedBothSigCodex;
export type IndexedBothSigCodexCode = (typeof IndexedBothSigCodex)[IndexedBothSigCodexName];
