// Generated by packages/cesr/scripts/generate-tables.ts
export const INDEXER_CODES = new Set<string>([
  "0A",
  "0B",
  "0z",
  "1z",
  "2A",
  "2B",
  "2C",
  "2D",
  "2E",
  "2F",
  "3A",
  "3B",
  "4z",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
]);

export const INDEXED_SIG_CODES = new Set<string>([
  "0A",
  "0B",
  "2A",
  "2B",
  "2C",
  "2D",
  "2E",
  "2F",
  "3A",
  "3B",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
]);

export const INDEXED_CURRENT_SIG_CODES = new Set<string>([
  "0B",
  "2B",
  "2D",
  "2F",
  "3B",
  "B",
  "D",
  "F",
]);

export const INDEXED_BOTH_SIG_CODES = new Set<string>([
  "0A",
  "2A",
  "2C",
  "2E",
  "3A",
  "A",
  "C",
  "E",
]);
