// Generated by packages/cesr/scripts/generate-tables.ts
export const BEXTER_CODES = new Set<string>([
  "4A",
  "5A",
  "6A",
  "7AAA",
  "8AAA",
  "9AAA",
]);

export const TEXTER_CODES = new Set<string>([
  "4B",
  "5B",
  "6B",
  "7AAB",
  "8AAB",
  "9AAB",
]);

export const DECIMAL_CODES = new Set<string>([
  "4H",
  "5H",
  "6H",
  "7AAH",
  "8AAH",
  "9AAH",
]);

export const DIGEST_CODES = new Set<string>([
  "0D",
  "0E",
  "0F",
  "0G",
  "E",
  "F",
  "G",
  "H",
  "I",
]);

export const NONCE_CODES = new Set<string>([
  "0A",
  "0D",
  "0E",
  "0F",
  "0G",
  "1AAP",
  "a",
  "E",
  "F",
  "G",
  "H",
  "I",
]);

export const NUMBER_CODES = new Set<string>([
  "0A",
  "0H",
  "M",
  "N",
  "R",
  "S",
  "T",
  "U",
]);

export const TAG_CODES = new Set<string>([
  "0J",
  "0K",
  "0L",
  "0M",
  "0N",
  "0O",
  "1AAF",
  "1AAN",
  "X",
  "Y",
  "Z",
]);

export const LABELER_CODES = new Set<string>([
  "0J",
  "0K",
  "0L",
  "0M",
  "0N",
  "0O",
  "1AAF",
  "1AAN",
  "1AAP",
  "4A",
  "4B",
  "5A",
  "5B",
  "6A",
  "6B",
  "7AAA",
  "7AAB",
  "8AAA",
  "8AAB",
  "9AAA",
  "9AAB",
  "V",
  "W",
  "X",
  "Y",
  "Z",
]);

export const PREFIX_CODES = new Set<string>([
  "0D",
  "0E",
  "0F",
  "0G",
  "1AAA",
  "1AAB",
  "1AAC",
  "1AAD",
  "1AAE",
  "1AAI",
  "1AAJ",
  "B",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
]);

export const NON_TRANSFERABLE_PREFIX_CODES = new Set<string>([
  "1AAA",
  "1AAC",
  "1AAI",
  "B",
]);

export const NON_DIGEST_PREFIX_CODES = new Set<string>([
  "1AAA",
  "1AAB",
  "1AAC",
  "1AAD",
  "1AAI",
  "1AAJ",
  "B",
  "D",
]);

export const ESCAPE_CODES = new Set<string>([
  "0J",
  "0K",
  "0L",
  "0M",
  "0N",
  "0O",
  "1AAF",
  "1AAK",
  "1AAL",
  "1AAM",
  "1AAN",
  "1AAO",
  "1AAP",
  "4A",
  "4B",
  "4H",
  "5A",
  "5B",
  "5H",
  "6A",
  "6B",
  "6H",
  "7AAA",
  "7AAB",
  "7AAH",
  "8AAA",
  "8AAB",
  "8AAH",
  "9AAA",
  "9AAB",
  "9AAH",
  "V",
  "W",
  "X",
  "Y",
  "Z",
]);

export const CIPHER_X25519_VARIABLE_STREAM_CODES = new Set<string>([
  "4C",
  "5C",
  "6C",
  "7AAC",
  "8AAC",
  "9AAC",
]);

export const CIPHER_X25519_QB64_VARIABLE_CODES = new Set<string>([
  "4D",
  "5D",
  "6D",
  "7AAD",
  "8AAD",
  "9AAD",
]);

export const CIPHER_X25519_FIXED_QB64_CODES = new Set<string>([
  "1AAH",
  "P",
]);

export const CIPHER_X25519_ALL_QB64_CODES = new Set<string>([
  "1AAH",
  "4D",
  "5D",
  "6D",
  "7AAD",
  "8AAD",
  "9AAD",
  "P",
]);

export const CIPHER_X25519_QB2_VARIABLE_CODES = new Set<string>([
  "4E",
  "5E",
  "6E",
  "7AAE",
  "8AAE",
  "9AAE",
]);

export const CIPHER_X25519_ALL_VARIABLE_CODES = new Set<string>([
  "4C",
  "4D",
  "4E",
  "5C",
  "5D",
  "5E",
  "6C",
  "6D",
  "6E",
  "7AAC",
  "7AAD",
  "7AAE",
  "8AAC",
  "8AAD",
  "8AAE",
  "9AAC",
  "9AAD",
  "9AAE",
]);

export const CIPHER_X25519_ALL_CODES = new Set<string>([
  "1AAH",
  "4C",
  "4D",
  "4E",
  "5C",
  "5D",
  "5E",
  "6C",
  "6D",
  "6E",
  "7AAC",
  "7AAD",
  "7AAE",
  "8AAC",
  "8AAD",
  "8AAE",
  "9AAC",
  "9AAD",
  "9AAE",
  "P",
]);
