// Generated by packages/cesr/scripts/generate-tables.ts
export const MatterCodex = Object.freeze(
  {
    Big: "N",
    Blake2b_256: "F",
    Blake2b_512: "0E",
    Blake2s_256: "G",
    Blake3_256: "E",
    Blake3_512: "0D",
    Bytes_Big_L0: "7AAB",
    Bytes_Big_L1: "8AAB",
    Bytes_Big_L2: "9AAB",
    Bytes_L0: "4B",
    Bytes_L1: "5B",
    Bytes_L2: "6B",
    DateTime: "1AAG",
    Decimal_Big_L0: "7AAH",
    Decimal_Big_L1: "8AAH",
    Decimal_Big_L2: "9AAH",
    Decimal_L0: "4H",
    Decimal_L1: "5H",
    Decimal_L2: "6H",
    ECDSA_256k1: "1AAB",
    ECDSA_256k1_Seed: "J",
    ECDSA_256k1_Sig: "0C",
    ECDSA_256k1N: "1AAA",
    ECDSA_256r1: "1AAJ",
    ECDSA_256r1_Seed: "Q",
    ECDSA_256r1_Sig: "0I",
    ECDSA_256r1N: "1AAI",
    Ed25519: "D",
    Ed25519_Seed: "A",
    Ed25519_Sig: "0B",
    Ed25519N: "B",
    Ed448: "1AAD",
    Ed448_Seed: "K",
    Ed448_Sig: "1AAE",
    Ed448N: "1AAC",
    Empty: "1AAP",
    Escape: "1AAO",
    GramHead: "0Q",
    GramHeadAID: "0S",
    GramHeadAIDNeck: "0R",
    GramHeadNeck: "0P",
    Great: "T",
    HPKEBase_Cipher_Big_L0: "7AAF",
    HPKEBase_Cipher_Big_L1: "8AAF",
    HPKEBase_Cipher_Big_L2: "9AAF",
    HPKEBase_Cipher_L0: "4F",
    HPKEBase_Cipher_L1: "5F",
    HPKEBase_Cipher_L2: "6F",
    Label1: "V",
    Label2: "W",
    Large: "S",
    Long: "0H",
    No: "1AAL",
    Null: "1AAK",
    Salt_128: "0A",
    Salt_256: "a",
    SHA2_256: "I",
    SHA2_512: "0G",
    SHA3_256: "H",
    SHA3_512: "0F",
    Short: "M",
    StrB64_Big_L0: "7AAA",
    StrB64_Big_L1: "8AAA",
    StrB64_Big_L2: "9AAA",
    StrB64_L0: "4A",
    StrB64_L1: "5A",
    StrB64_L2: "6A",
    Tag1: "0J",
    Tag10: "0O",
    Tag11: "Z",
    Tag2: "0K",
    Tag3: "X",
    Tag4: "1AAF",
    Tag5: "0L",
    Tag6: "0M",
    Tag7: "Y",
    Tag8: "1AAN",
    Tag9: "0N",
    Tall: "R",
    TBD0: "1___",
    TBD0S: "1__-",
    TBD1: "2___",
    TBD1S: "2__-",
    TBD2: "3___",
    TBD2S: "3__-",
    Vast: "U",
    X25519: "C",
    X25519_Cipher_Big_L0: "7AAC",
    X25519_Cipher_Big_L1: "8AAC",
    X25519_Cipher_Big_L2: "9AAC",
    X25519_Cipher_L0: "4C",
    X25519_Cipher_L1: "5C",
    X25519_Cipher_L2: "6C",
    X25519_Cipher_QB2_Big_L0: "7AAE",
    X25519_Cipher_QB2_Big_L1: "8AAE",
    X25519_Cipher_QB2_Big_L2: "9AAE",
    X25519_Cipher_QB2_L0: "4E",
    X25519_Cipher_QB2_L1: "5E",
    X25519_Cipher_QB2_L2: "6E",
    X25519_Cipher_QB64_Big_L0: "7AAD",
    X25519_Cipher_QB64_Big_L1: "8AAD",
    X25519_Cipher_QB64_Big_L2: "9AAD",
    X25519_Cipher_QB64_L0: "4D",
    X25519_Cipher_QB64_L1: "5D",
    X25519_Cipher_QB64_L2: "6D",
    X25519_Cipher_Salt: "1AAH",
    X25519_Cipher_Seed: "P",
    X25519_Private: "O",
    X448: "L",
    Yes: "1AAM",
  } as const,
);

export const MtrDex = MatterCodex;

export type MatterCodexName = keyof typeof MatterCodex;
export type MatterCodexCode = (typeof MatterCodex)[MatterCodexName];

export const SmallVarRawSizeCodex = Object.freeze(
  {
    Lead0: "4",
    Lead1: "5",
    Lead2: "6",
  } as const,
);

export const SmallVrzDex = SmallVarRawSizeCodex;

export type SmallVarRawSizeCodexName = keyof typeof SmallVarRawSizeCodex;
export type SmallVarRawSizeCodexCode =
  (typeof SmallVarRawSizeCodex)[SmallVarRawSizeCodexName];

export const LargeVarRawSizeCodex = Object.freeze(
  {
    Lead0_Big: "7",
    Lead1_Big: "8",
    Lead2_Big: "9",
  } as const,
);

export const LargeVrzDex = LargeVarRawSizeCodex;

export type LargeVarRawSizeCodexName = keyof typeof LargeVarRawSizeCodex;
export type LargeVarRawSizeCodexCode =
  (typeof LargeVarRawSizeCodex)[LargeVarRawSizeCodexName];

export const BextCodex = Object.freeze(
  {
    StrB64_Big_L0: "7AAA",
    StrB64_Big_L1: "8AAA",
    StrB64_Big_L2: "9AAA",
    StrB64_L0: "4A",
    StrB64_L1: "5A",
    StrB64_L2: "6A",
  } as const,
);

export const BexDex = BextCodex;

export type BextCodexName = keyof typeof BextCodex;
export type BextCodexCode = (typeof BextCodex)[BextCodexName];

export const TextCodex = Object.freeze(
  {
    Bytes_Big_L0: "7AAB",
    Bytes_Big_L1: "8AAB",
    Bytes_Big_L2: "9AAB",
    Bytes_L0: "4B",
    Bytes_L1: "5B",
    Bytes_L2: "6B",
  } as const,
);

export const TexDex = TextCodex;

export type TextCodexName = keyof typeof TextCodex;
export type TextCodexCode = (typeof TextCodex)[TextCodexName];

export const DecimalCodex = Object.freeze(
  {
    Decimal_Big_L0: "7AAH",
    Decimal_Big_L1: "8AAH",
    Decimal_Big_L2: "9AAH",
    Decimal_L0: "4H",
    Decimal_L1: "5H",
    Decimal_L2: "6H",
  } as const,
);

export const DecDex = DecimalCodex;

export type DecimalCodexName = keyof typeof DecimalCodex;
export type DecimalCodexCode = (typeof DecimalCodex)[DecimalCodexName];

export const DigCodex = Object.freeze(
  {
    Blake2b_256: "F",
    Blake2b_512: "0E",
    Blake2s_256: "G",
    Blake3_256: "E",
    Blake3_512: "0D",
    SHA2_256: "I",
    SHA2_512: "0G",
    SHA3_256: "H",
    SHA3_512: "0F",
  } as const,
);

export const DigDex = DigCodex;

export type DigCodexName = keyof typeof DigCodex;
export type DigCodexCode = (typeof DigCodex)[DigCodexName];

export const NonceCodex = Object.freeze(
  {
    Blake2b_256: "F",
    Blake2b_512: "0E",
    Blake2s_256: "G",
    Blake3_256: "E",
    Blake3_512: "0D",
    Empty: "1AAP",
    Salt_128: "0A",
    Salt_256: "a",
    SHA2_256: "I",
    SHA2_512: "0G",
    SHA3_256: "H",
    SHA3_512: "0F",
  } as const,
);

export const NonceDex = NonceCodex;

export type NonceCodexName = keyof typeof NonceCodex;
export type NonceCodexCode = (typeof NonceCodex)[NonceCodexName];

export const NumCodex = Object.freeze(
  {
    Big: "N",
    Great: "T",
    Huge: "0A",
    Large: "S",
    Long: "0H",
    Short: "M",
    Tall: "R",
    Vast: "U",
  } as const,
);

export const NumDex = NumCodex;

export type NumCodexName = keyof typeof NumCodex;
export type NumCodexCode = (typeof NumCodex)[NumCodexName];

export const TagCodex = Object.freeze(
  {
    Tag1: "0J",
    Tag10: "0O",
    Tag11: "Z",
    Tag2: "0K",
    Tag3: "X",
    Tag4: "1AAF",
    Tag5: "0L",
    Tag6: "0M",
    Tag7: "Y",
    Tag8: "1AAN",
    Tag9: "0N",
  } as const,
);

export const TagDex = TagCodex;

export type TagCodexName = keyof typeof TagCodex;
export type TagCodexCode = (typeof TagCodex)[TagCodexName];

export const LabelCodex = Object.freeze(
  {
    Bytes_Big_L0: "7AAB",
    Bytes_Big_L1: "8AAB",
    Bytes_Big_L2: "9AAB",
    Bytes_L0: "4B",
    Bytes_L1: "5B",
    Bytes_L2: "6B",
    Empty: "1AAP",
    Label1: "V",
    Label2: "W",
    StrB64_Big_L0: "7AAA",
    StrB64_Big_L1: "8AAA",
    StrB64_Big_L2: "9AAA",
    StrB64_L0: "4A",
    StrB64_L1: "5A",
    StrB64_L2: "6A",
    Tag1: "0J",
    Tag10: "0O",
    Tag11: "Z",
    Tag2: "0K",
    Tag3: "X",
    Tag4: "1AAF",
    Tag5: "0L",
    Tag6: "0M",
    Tag7: "Y",
    Tag8: "1AAN",
    Tag9: "0N",
  } as const,
);

export const LabelDex = LabelCodex;

export type LabelCodexName = keyof typeof LabelCodex;
export type LabelCodexCode = (typeof LabelCodex)[LabelCodexName];

export const PreCodex = Object.freeze(
  {
    Blake2b_256: "F",
    Blake2b_512: "0E",
    Blake2s_256: "G",
    Blake3_256: "E",
    Blake3_512: "0D",
    ECDSA_256k1: "1AAB",
    ECDSA_256k1N: "1AAA",
    ECDSA_256r1: "1AAJ",
    ECDSA_256r1N: "1AAI",
    Ed25519: "D",
    Ed25519N: "B",
    Ed448: "1AAD",
    Ed448_Sig: "1AAE",
    Ed448N: "1AAC",
    SHA2_256: "I",
    SHA2_512: "0G",
    SHA3_256: "H",
    SHA3_512: "0F",
  } as const,
);

export const PreDex = PreCodex;

export type PreCodexName = keyof typeof PreCodex;
export type PreCodexCode = (typeof PreCodex)[PreCodexName];

export const NonTransCodex = Object.freeze(
  {
    ECDSA_256k1N: "1AAA",
    ECDSA_256r1N: "1AAI",
    Ed25519N: "B",
    Ed448N: "1AAC",
  } as const,
);

export const NonTransDex = NonTransCodex;

export type NonTransCodexName = keyof typeof NonTransCodex;
export type NonTransCodexCode = (typeof NonTransCodex)[NonTransCodexName];

export const PreNonDigCodex = Object.freeze(
  {
    ECDSA_256k1: "1AAB",
    ECDSA_256k1N: "1AAA",
    ECDSA_256r1: "1AAJ",
    ECDSA_256r1N: "1AAI",
    Ed25519: "D",
    Ed25519N: "B",
    Ed448: "1AAD",
    Ed448N: "1AAC",
  } as const,
);

export const PreNonDigDex = PreNonDigCodex;

export type PreNonDigCodexName = keyof typeof PreNonDigCodex;
export type PreNonDigCodexCode = (typeof PreNonDigCodex)[PreNonDigCodexName];

export const EscapeCodex = Object.freeze(
  {
    Bytes_Big_L0: "7AAB",
    Bytes_Big_L1: "8AAB",
    Bytes_Big_L2: "9AAB",
    Bytes_L0: "4B",
    Bytes_L1: "5B",
    Bytes_L2: "6B",
    Decimal_Big_L0: "7AAH",
    Decimal_Big_L1: "8AAH",
    Decimal_Big_L2: "9AAH",
    Decimal_L0: "4H",
    Decimal_L1: "5H",
    Decimal_L2: "6H",
    Empty: "1AAP",
    Escape: "1AAO",
    Label1: "V",
    Label2: "W",
    No: "1AAL",
    Null: "1AAK",
    StrB64_Big_L0: "7AAA",
    StrB64_Big_L1: "8AAA",
    StrB64_Big_L2: "9AAA",
    StrB64_L0: "4A",
    StrB64_L1: "5A",
    StrB64_L2: "6A",
    Tag1: "0J",
    Tag10: "0O",
    Tag11: "Z",
    Tag2: "0K",
    Tag3: "X",
    Tag4: "1AAF",
    Tag5: "0L",
    Tag6: "0M",
    Tag7: "Y",
    Tag8: "1AAN",
    Tag9: "0N",
    Yes: "1AAM",
  } as const,
);

export const EscapeDex = EscapeCodex;

export type EscapeCodexName = keyof typeof EscapeCodex;
export type EscapeCodexCode = (typeof EscapeCodex)[EscapeCodexName];

export const CipherX25519VarStrmCodex = Object.freeze(
  {
    X25519_Cipher_Big_L0: "7AAC",
    X25519_Cipher_Big_L1: "8AAC",
    X25519_Cipher_Big_L2: "9AAC",
    X25519_Cipher_L0: "4C",
    X25519_Cipher_L1: "5C",
    X25519_Cipher_L2: "6C",
  } as const,
);

export const CiXVarStrmDex = CipherX25519VarStrmCodex;

export type CipherX25519VarStrmCodexName =
  keyof typeof CipherX25519VarStrmCodex;
export type CipherX25519VarStrmCodexCode =
  (typeof CipherX25519VarStrmCodex)[CipherX25519VarStrmCodexName];

export const CipherX25519VarQB64Codex = Object.freeze(
  {
    X25519_Cipher_QB64_Big_L0: "7AAD",
    X25519_Cipher_QB64_Big_L1: "8AAD",
    X25519_Cipher_QB64_Big_L2: "9AAD",
    X25519_Cipher_QB64_L0: "4D",
    X25519_Cipher_QB64_L1: "5D",
    X25519_Cipher_QB64_L2: "6D",
  } as const,
);

export const CiXVarQB64Dex = CipherX25519VarQB64Codex;

export type CipherX25519VarQB64CodexName =
  keyof typeof CipherX25519VarQB64Codex;
export type CipherX25519VarQB64CodexCode =
  (typeof CipherX25519VarQB64Codex)[CipherX25519VarQB64CodexName];

export const CipherX25519FixQB64Codex = Object.freeze(
  {
    X25519_Cipher_Salt: "1AAH",
    X25519_Cipher_Seed: "P",
  } as const,
);

export const CiXFixQB64Dex = CipherX25519FixQB64Codex;

export type CipherX25519FixQB64CodexName =
  keyof typeof CipherX25519FixQB64Codex;
export type CipherX25519FixQB64CodexCode =
  (typeof CipherX25519FixQB64Codex)[CipherX25519FixQB64CodexName];

export const CipherX25519AllQB64Codex = Object.freeze(
  {
    X25519_Cipher_QB64_Big_L0: "7AAD",
    X25519_Cipher_QB64_Big_L1: "8AAD",
    X25519_Cipher_QB64_Big_L2: "9AAD",
    X25519_Cipher_QB64_L0: "4D",
    X25519_Cipher_QB64_L1: "5D",
    X25519_Cipher_QB64_L2: "6D",
    X25519_Cipher_Salt: "1AAH",
    X25519_Cipher_Seed: "P",
  } as const,
);

export const CiXAllQB64Dex = CipherX25519AllQB64Codex;

export type CipherX25519AllQB64CodexName =
  keyof typeof CipherX25519AllQB64Codex;
export type CipherX25519AllQB64CodexCode =
  (typeof CipherX25519AllQB64Codex)[CipherX25519AllQB64CodexName];

export const CipherX25519QB2VarCodex = Object.freeze(
  {
    X25519_Cipher_QB2_Big_L0: "7AAE",
    X25519_Cipher_QB2_Big_L1: "8AAE",
    X25519_Cipher_QB2_Big_L2: "9AAE",
    X25519_Cipher_QB2_L0: "4E",
    X25519_Cipher_QB2_L1: "5E",
    X25519_Cipher_QB2_L2: "6E",
  } as const,
);

export const CiXVarQB2Dex = CipherX25519QB2VarCodex;

export type CipherX25519QB2VarCodexName = keyof typeof CipherX25519QB2VarCodex;
export type CipherX25519QB2VarCodexCode =
  (typeof CipherX25519QB2VarCodex)[CipherX25519QB2VarCodexName];

export const CipherX25519AllVarCodex = Object.freeze(
  {
    X25519_Cipher_Big_L0: "7AAC",
    X25519_Cipher_Big_L1: "8AAC",
    X25519_Cipher_Big_L2: "9AAC",
    X25519_Cipher_L0: "4C",
    X25519_Cipher_L1: "5C",
    X25519_Cipher_L2: "6C",
    X25519_Cipher_QB2_Big_L0: "7AAE",
    X25519_Cipher_QB2_Big_L1: "8AAE",
    X25519_Cipher_QB2_Big_L2: "9AAE",
    X25519_Cipher_QB2_L0: "4E",
    X25519_Cipher_QB2_L1: "5E",
    X25519_Cipher_QB2_L2: "6E",
    X25519_Cipher_QB64_Big_L0: "7AAD",
    X25519_Cipher_QB64_Big_L1: "8AAD",
    X25519_Cipher_QB64_Big_L2: "9AAD",
    X25519_Cipher_QB64_L0: "4D",
    X25519_Cipher_QB64_L1: "5D",
    X25519_Cipher_QB64_L2: "6D",
  } as const,
);

export const CiXVarDex = CipherX25519AllVarCodex;

export type CipherX25519AllVarCodexName = keyof typeof CipherX25519AllVarCodex;
export type CipherX25519AllVarCodexCode =
  (typeof CipherX25519AllVarCodex)[CipherX25519AllVarCodexName];

export const CipherX25519AllCodex = Object.freeze(
  {
    X25519_Cipher_Big_L0: "7AAC",
    X25519_Cipher_Big_L1: "8AAC",
    X25519_Cipher_Big_L2: "9AAC",
    X25519_Cipher_L0: "4C",
    X25519_Cipher_L1: "5C",
    X25519_Cipher_L2: "6C",
    X25519_Cipher_QB2_Big_L0: "7AAE",
    X25519_Cipher_QB2_Big_L1: "8AAE",
    X25519_Cipher_QB2_Big_L2: "9AAE",
    X25519_Cipher_QB2_L0: "4E",
    X25519_Cipher_QB2_L1: "5E",
    X25519_Cipher_QB2_L2: "6E",
    X25519_Cipher_QB64_Big_L0: "7AAD",
    X25519_Cipher_QB64_Big_L1: "8AAD",
    X25519_Cipher_QB64_Big_L2: "9AAD",
    X25519_Cipher_QB64_L0: "4D",
    X25519_Cipher_QB64_L1: "5D",
    X25519_Cipher_QB64_L2: "6D",
    X25519_Cipher_Salt: "1AAH",
    X25519_Cipher_Seed: "P",
  } as const,
);

export const CiXDex = CipherX25519AllCodex;

export type CipherX25519AllCodexName = keyof typeof CipherX25519AllCodex;
export type CipherX25519AllCodexCode =
  (typeof CipherX25519AllCodex)[CipherX25519AllCodexName];
