// Generated by scripts/generate-tables.ts
import type { Sizage } from "./table-types.ts";

export const MATTER_SIZES = new Map<string, Sizage>([
  ["A", { hs: 1, ss: 0, xs: 0, fs: 44, ls: 0 }],
  ["B", { hs: 1, ss: 0, xs: 0, fs: 44, ls: 0 }],
  ["C", { hs: 1, ss: 0, xs: 0, fs: 44, ls: 0 }],
  ["D", { hs: 1, ss: 0, xs: 0, fs: 44, ls: 0 }],
  ["E", { hs: 1, ss: 0, xs: 0, fs: 44, ls: 0 }],
  ["F", { hs: 1, ss: 0, xs: 0, fs: 44, ls: 0 }],
  ["G", { hs: 1, ss: 0, xs: 0, fs: 44, ls: 0 }],
  ["H", { hs: 1, ss: 0, xs: 0, fs: 44, ls: 0 }],
  ["I", { hs: 1, ss: 0, xs: 0, fs: 44, ls: 0 }],
  ["J", { hs: 1, ss: 0, xs: 0, fs: 44, ls: 0 }],
  ["K", { hs: 1, ss: 0, xs: 0, fs: 76, ls: 0 }],
  ["L", { hs: 1, ss: 0, xs: 0, fs: 76, ls: 0 }],
  ["M", { hs: 1, ss: 0, xs: 0, fs: 4, ls: 0 }],
  ["N", { hs: 1, ss: 0, xs: 0, fs: 12, ls: 0 }],
  ["0A", { hs: 2, ss: 0, xs: 0, fs: 24, ls: 0 }],
  ["0B", { hs: 2, ss: 0, xs: 0, fs: 88, ls: 0 }],
  ["0C", { hs: 2, ss: 0, xs: 0, fs: 88, ls: 0 }],
  ["0D", { hs: 2, ss: 0, xs: 0, fs: 88, ls: 0 }],
  ["0E", { hs: 2, ss: 0, xs: 0, fs: 88, ls: 0 }],
  ["0F", { hs: 2, ss: 0, xs: 0, fs: 88, ls: 0 }],
  ["0G", { hs: 2, ss: 0, xs: 0, fs: 88, ls: 0 }],
  ["0H", { hs: 2, ss: 0, xs: 0, fs: 8, ls: 0 }],
  ["0I", { hs: 2, ss: 0, xs: 0, fs: 88, ls: 0 }],
  ["1AAG", { hs: 4, ss: 0, xs: 0, fs: 36, ls: 1 }],
  ["1AAH", { hs: 4, ss: 0, xs: 0, fs: 100, ls: 0 }],
  ["1AAI", { hs: 4, ss: 0, xs: 0, fs: 48, ls: 1 }],
  ["1AAJ", { hs: 4, ss: 0, xs: 0, fs: 48, ls: 1 }],
  ["1AAK", { hs: 4, ss: 0, xs: 0, fs: 4, ls: 0 }],
  ["4A", { hs: 2, ss: 2, xs: 0, fs: null, ls: 0 }],
  ["5A", { hs: 2, ss: 2, xs: 0, fs: null, ls: 1 }],
  ["6A", { hs: 2, ss: 2, xs: 0, fs: null, ls: 2 }],
  ["7AAA", { hs: 4, ss: 4, xs: 0, fs: null, ls: 0 }],
  ["8AAA", { hs: 4, ss: 4, xs: 0, fs: null, ls: 1 }],
  ["9AAA", { hs: 4, ss: 4, xs: 0, fs: null, ls: 2 }],
  ["4B", { hs: 2, ss: 2, xs: 0, fs: null, ls: 0 }],
  ["5B", { hs: 2, ss: 2, xs: 0, fs: null, ls: 1 }],
  ["6B", { hs: 2, ss: 2, xs: 0, fs: null, ls: 2 }],
  ["7AAB", { hs: 4, ss: 4, xs: 0, fs: null, ls: 0 }],
  ["8AAB", { hs: 4, ss: 4, xs: 0, fs: null, ls: 1 }],
  ["9AAB", { hs: 4, ss: 4, xs: 0, fs: null, ls: 2 }],
]);

export const MATTER_HARDS = new Map<string, number>([
  ..."ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map((c) =>
    [c, 1] as [string, number]
  ),
  ..."abcdefghijklmnopqrstuvwxyz".split("").map((c) =>
    [c, 1] as [string, number]
  ),
  ["0", 2],
  ["1", 4],
  ["2", 4],
  ["3", 4],
  ["4", 2],
  ["5", 2],
  ["6", 2],
  ["7", 4],
  ["8", 4],
  ["9", 4],
]);
