// Generated by packages/cesr/scripts/generate-tables.ts
export const TraitCodex = Object.freeze(
  {
    DelegateIsDelegator: "DID",
    DoNotDelegate: "DND",
    EstOnly: "EO",
    NoBackers: "NB",
    NoRegistrarBackers: "NRB",
    RegistrarBackers: "RB",
  } as const,
);

export const TraitDex = TraitCodex;

export type TraitCodexName = keyof typeof TraitCodex;
export type TraitCodexCode = (typeof TraitCodex)[TraitCodexName];
