/**
 * Generated by scripts/generate_versions.ts.
 * Do not edit by hand.
 */
export const PACKAGE_VERSION = "0.2.1";
export const BUILD_METADATA = "";
export const DISPLAY_VERSION = BUILD_METADATA
  ? `${PACKAGE_VERSION}+${BUILD_METADATA}`
  : PACKAGE_VERSION;
