name: keri-ts npm release

on:
  push:
    tags: ["keri-v*"]
  workflow_dispatch:
    inputs:
      publish:
        description: Publish to npm
        required: true
        default: false
        type: boolean

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: ./.github/workflows/npm-release.yml
    with:
      package: keri
      publish: ${{ github.event_name == 'push' || inputs.publish }}
